[pytest]

pythonpath = .

markers =
    unit: Unit tests
    service: Service tests
    util : Util tests
    integration: integration tests
    repository: repository tests
    controller: controller tests

testpaths =
    tests